### ISSUE TITLE
Enemy affinity & attacks

### ISSUE THREAD

**Issue by headbox8424** [calamity-inc/warframe-public-export-plus#11]
Is it possible to know the affinity and attack value of enemies?

and also procresist and weakpoints as well?

**Comment by Sainan** [comment]
Some of these are obvious, but what do you mean e.g. by "attack value"? In general it would be good to have an idea of what you'd want to see.

**Comment by headbox8424** [comment]
I mean attack distribution of enemy weapons.

Like the below ones. (Ballista and Amalgam Satyr)
![Screenshot_20240715_214934_Chrome](https://github.com/user-attachments/assets/d791042d-543b-4e88-b75c-25440465602d)
![Screenshot_20240715_214945_Chrome](https://github.com/user-attachments/assets/f07e9468-c1fa-4a83-a320-c45621138b6e)

**Comment by Sainan** [comment]
Hmm, well, I think that's based on their weapons, which are unfortunately not weapons that are already in ExportWeapons or somewhere.

**Comment by headbox8424** [comment]
I see.... Then are the rest of them possible?

**Comment by Sainan** [comment]
I'm not saying that it's impossible, but you also gave me quite the laundry list. :P

**Comment by headbox8424** [comment]
Sry i left you with bunch of jobs. I have no idea how you do it.

**Comment by Sainan** [comment]
Well, I added affinity and "items" (some are actually already in ExportWeapons).

I will try to export the enemy-exclusive weapons at some point in the future.

Could you also clarify on "procresist" and "weakpoints"?

**Comment by headbox8424** [comment]
Thanks :)

Enemies with Status immunity (like bosses or some Deimos enemies)

Body multiplier (3x to head for most enemies, corpus MOAs 3x to backs)

**Comment by Sainan** [comment]
> Enemies with Status immunity (like bosses or some Deimos enemies)

I'm still not quite sure, because there's like multiple things this could mean. You mean like they can't be knocked down or teleported, or they can't be afflicted a certain status proc?

> Body multiplier (3x to head for most enemies, corpus MOAs 3x to backs)

I have a decent idea for this, although some of the data I'm seeing contradicts the wiki data, but I guess I can add it.

**Comment by headbox8424** [comment]
I was talking certain status proc, but it seems nice to include them too.

**Comment by Sainan** [comment]
Like, I do know you can't stagger, stun, or ragdoll an acolyte for example, but I'm not actually aware of any examples of "status immunity". What are you thinking of?

**Comment by headbox8424** [comment]
[Status Effect#Status Immune Enemies](https://warframe.fandom.com/wiki/Status_Effect#Status_Immune_Enemies)

Here's some example of them but they're incomplete

**Comment by Sainan** [comment]
Okay, I've added unhandledProcTypes now, which I think is what you're looking for. Let me know otherwise.

**Comment by Sainan** [comment]
Added hitProxies now as well.

**Comment by headbox8424** [comment]
Thanks a lot! You are a savior

**Comment by Sainan** [comment]
Well, I still haven't added the enemy-exclusive weapons yet. It that irrelevant, or?

**Comment by headbox8424** [comment]
Of course that would be nice. Anyway I gotta stick with this for a while.

**Comment by Sainan** [comment]
Stick with this?

**Comment by headbox8424** [comment]
No, just saying. What I meant was that I will try hard with this now.

**Comment by Sainan** [comment]
I've now added `aiWeapons` to ExportEnemies. So, for the enemy attacks, simply check the items of the agent, and if the item is in ExportWeapons or aiWeapons, you can see the weapon behaviours. Let me know if there's anything missing.
